name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t my-food-app .
          docker tag my-food-app YOUR_DOCKER_HUB_USERNAME/my-food-app:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push YOUR_DOCKER_HUB_USERNAME/my-food-app:latest

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << EOF
            docker pull YOUR_DOCKER_HUB_USERNAME/my-food-app:latest
            docker stop my-food-app || true
            docker rm my-food-app || true
            docker run -d -p 80:80 --name my-food-app YOUR_DOCKER_HUB_USERNAME/my-food-app:latest
          EOF
